# GH actions

name: unittest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4
